import keyMirror from 'keymirror';

export default keyMirror({
  DASHBOARD_LOAD_COMPLETE: null,
  DASHBOARD_ITEM_TOGGLE: null,
  DASHBOARD_PRODUCT_TOGGLE: null,
  DASHBOARD_SAVE_SELECTION_NEXT_DASHBOARD: null,
  DASHBOARD_EXPAND_NEXT_DASHBOARD: null,
  DASHBOARD_REMOVE_SELECTED_PRODUCTS_CURRENT_DASHBOARD: null,
  DASHBOARD_MOVE_SELECTED_PRODUCT_TO_DASHBOARD: null,
  DASHBOARD_NEXT_DASHBOARD_CHANGE: null,
  DASHBOARD_CHANGE_EVENT: null
});
